---
title: "circos"
author: "Aaron Mohammed"
date: "2022-10-27"
output: html_document
---

```{r}

library(circlize)
library(tidyr)

```

```{r}

# Path to tissue directories that contain the data
path_to_RData <- c("/Users/asm/Creighton/celegan/Modules")

# Path to output directory for circos plots
plots_path <- file.path(path_to_RData, 'circos_plots')
dir.create(plots_path)

```

```{r}

# List the tissue directories that will be analyzed. This is just to get their names.
tissuez <- list.dirs('/Users/asm/Creighton/celegan/Bootstrap/_tissues_with_3_N2_timepoints',
                     full.names=FALSE, 
                     recursive= FALSE)

# Remove embryonic cells
tissuez <- tissuez[-1] 


# tissuez <- c("Germline", "Hypodermis", "Intestine", "Muscle", "Neuron", "Pharynx", "Vulva_uterus")

```

```{r}

circos.plot <- function (tissue) {
  
  tissue_dir <- file.path(path_to_RData, tissue)
  
  overlap_file_name <- list.files(tissue_dir, pattern="overlap")
  overlap <- read.csv(file.path(tissue_dir, overlap_file_name))
  overlap <- overlap[,-1]
  
  CP_N2_file_name <- list.files(tissue_dir, pattern="CP_N2")
  CP_LIPL4_file_name <- list.files(tissue_dir, pattern="CP_LIPL4")
  CP_DAF2_file_name <- list.files(tissue_dir, pattern="CP_DAF2")
  CP_RSKS1_file_name <- list.files(tissue_dir, pattern="CP_RSKS1")
  
  CP_N2 <- readRDS(file= file.path(tissue_dir, CP_N2_file_name))
  CP_LIPL4 <- readRDS(file= file.path(tissue_dir, CP_LIPL4_file_name))
  CP_DAF2 <- readRDS(file= file.path(tissue_dir, CP_DAF2_file_name))
  CP_RSKS1 <- readRDS(file= file.path(tissue_dir, CP_RSKS1_file_name))
  
  CP_list <- list(CP_N2 , CP_LIPL4, CP_DAF2, CP_RSKS1)
  names(CP_list) <- c("N2","LIPL4","DAF2","RSKS1")
  
  ##############################################################################
  
  filtered <- overlap[overlap$pval<0.05,]
  
  # Remove duplicate combinations (I did this based on pvalues. Duplicate combinations 
  # should have pvalues that are identical up to 3 significant figures)
  filtered <- filtered[!duplicated(signif(filtered$pval,3)), ] 
  
  connections <- filtered[,c(1,2,6)]
  
  ##############################################################################
  
  # This section is for determining the sizes of each sector
  geno_sizes <- overlap[,c(1,3)]
  geno_sizes2 <- overlap[,c(2,4)]
  geno_sizes <- geno_sizes[!duplicated(geno_sizes),]
  geno_sizes2 <- geno_sizes2[!duplicated(geno_sizes2),]
  names(geno_sizes) <- c("module", "size")
  names(geno_sizes2) <- c("module", "size")
  geno_sizes <- rbind(geno_sizes,geno_sizes2)
  geno_sizes <- geno_sizes[!duplicated(geno_sizes),]
  
  geno_module_sizes <- separate(data= geno_sizes, col= module, into= c("genotype", "module"), sep = "\\_")
  
  ngenes_genotype <- aggregate(geno_module_sizes$size, by=list(Category=geno_module_sizes$genotype), FUN=sum)
  names(ngenes_genotype) <- c("genotype", "size")
  ngenes_genotype$proportion <- proportions(ngenes_genotype$size)
  
  geno_module_sizes$total_geno_size <- NA
  geno_module_sizes$proportion <- NA
  
  ##############################################################################
  
  genoz <- ngenes_genotype$genotype
  
  for (i in 1:length(genoz)) {
    geno_module_sizes$total_geno_size[geno_module_sizes$genotype==genoz[i]] <- ngenes_genotype$size[ngenes_genotype$genotype==genoz[i]]
  }
  
  geno_module_sizes$proportion <- geno_module_sizes$size/geno_module_sizes$total_geno_size
  
  split_tibble <- function(tibble, col = 'col') tibble %>% split(., .[, col])
  mod_list <- split_tibble(geno_module_sizes, 'genotype')
  
  for (i in 1:length(genoz)) {
    mod_list[[genoz[i]]] <- mod_list[[genoz[i]]][order(mod_list[[genoz[i]]]$proportion), ]
  }
  
  for (i in 1:length(genoz)) {
    mod_list[[genoz[i]]]$end_position[1] <- mod_list[[genoz[i]]]$proportion[1]
    L <- nrow(mod_list[[genoz[i]]])
    R <- 2
    while (R <= L) {
      mod_list[[genoz[i]]]$end_position[R] <- mod_list[[genoz[i]]]$proportion[R] + mod_list[[genoz[i]]]$end_position[R-1]
      R = R + 1
    }
  }
  
  for (i in 1:length(genoz)) {
    mod_list[[genoz[i]]]$geno_mod <- paste(mod_list[[genoz[i]]]$genotype, 
                                           mod_list[[genoz[i]]]$module, 
                                           sep= "_")
  }
  
  for (i in 1:length(genoz)) {
    for (j in 1:nrow(mod_list[[genoz[i]]])) {
      mod <- mod_list[[genoz[i]]]$geno_mod[j]
      mod_list[[genoz[i]]]$cor[j] <- CP_list[[genoz[i]]][mod,"cor"]
    }
  }

  ##############################################################################
                                  # Circos Plot
  ##############################################################################
  
  circos_file_name <- paste(tissue, sep= "_", 'circos_plot.pdf')
  
  pdf(file.path(plots_path, circos_file_name), width = 8, height = 8)
  
  geno_color <- c(2,3,4,6)
  circos.par("track.height" = 0.05, gap.after = c(4,4,4,4), cell.padding = c(0, 0, 0, 0))
  circos.initialize(genoz, xlim = c(0, 1),sector.width = ngenes_genotype$proportion)
  circos.track(ylim = c(0,1))
  circos.track(ylim = c(0,1),track.height =0.08)
  
  title(tissue)
  
  # Add line segments that split the modules of each genotype
  for (i in 1:length(genoz)) {
    for (j in 1:nrow(mod_list[[genoz[i]]])) {
      x <- mod_list[[genoz[i]]]$end_position[j]
      circos.segments(x,0,x,1, 
                      sector.index = genoz[i], 
                      track.index = 2)
    }
  }
  
  # Color the modules based on their correlation with aging
  for (i in 1:length(genoz)) {
    
    for (j in 1:nrow(mod_list[[genoz[i]]])) {
      xi <- mod_list[[genoz[i]]]$end_position[j-1]
      x <- mod_list[[genoz[i]]]$end_position[j]
      cor <- mod_list[[genoz[i]]]$cor[j]
      
      if (cor > 0) {color = "green"}
      if (cor < 0) {color = "blue"}
      
      if (j == 1) {
        circos.rect(0, 0, x, 1, 
                    col= color, 
                    sector.index = genoz[i], 
                    track.index = 2)
      }
      else {
        circos.rect(xi, 0, x, 1, 
                    col= color, 
                    sector.index = genoz[i], 
                    track.index = 2)
      }
    }
  }
  
  # Add the links between modules
  transp <- 0.8
  
  skip_these <- data.frame(matrix(nrow=1,ncol=2))
  names(skip_these) <- c("M1","M2")
  
  for (geno in genoz) {
    
    modulez <- connections[grep(geno, connections$M1) ,]
    modulez <- rbind(modulez, connections[grep(geno, connections$M2) ,])
    modulez[grep(geno, modulez$M2), c("M2","M1")] <- modulez[grep(geno, modulez$M2), c("M1","M2")]
    
    
    t <- table(modulez$M1)
    dup_1 <- names(which(t[]>1)) 
  
    if (!identical(dup_1, character(0))) {
      for (i in 1:length(dup_1)) {
        loc <- grep(dup_1[i], modulez$M1)
        modulez <- separate(data= modulez, col= M2, into= c("genotype", "module"), sep = "\\_")
        dummy_mod_1 <- data.frame(matrix(nrow= nrow(modulez), ncol= ncol(modulez)))
        dummy_mod_1[loc,] <- modulez[loc,]
        t <- table(dummy_mod_1[,2])
        dup_g <- names(which(t[]>1)) 
        
        if (!identical(dup_g, character(0))) {
          for (j in 1:length(dup_g)) {
            loc <- which(dummy_mod_1[,2] == dup_g[j])
            dummy_mod_2 <- c(rep(NA,nrow(modulez)))
            dummy_mod_2[loc] <- modulez$pval[loc]
            loc_min <- which.min(dummy_mod_2)
            loc_remove <- loc[loc != loc_min]
            modulez <- modulez[-loc_remove,]
          }
        }
        modulez <- modulez %>% unite("M2", genotype:module, sep= "_", remove= TRUE)
      }
    }
    
    
    t <- table(modulez$M2)
    dup_2 <- names(which(t[]>1)) 
  
    if (!identical(dup_2, character(0))) {
      for (i in 1:length(dup_2)) {
        loc <- grep(dup_2[i], modulez$M2)
        dummy_mod <- c(rep(NA,nrow(modulez)))
        dummy_mod[loc] <- modulez$pval[loc]
        loc_min <- which.min(dummy_mod)
        loc_remove <- loc[loc != loc_min]
        modulez <- modulez[-loc_remove,]
      }}
    
    
    
    for (i in 1:nrow(modulez)) {
      M1 <- modulez$M1[i]
      M2 <- modulez$M2[i]
      
      test1 <- which(skip_these$M1 == M1 & skip_these$M2 == M2)
      test2 <- which(skip_these$M1 == M2 & skip_these$M2 == M1)
      
      if (!identical(test1,integer(0)) | !identical(test2,integer(0))) next
      
      geno1 <- gsub("_.*","",M1)
      geno2 <- gsub("_.*","",M2)
      
      loc_a <- which(mod_list[[geno1]]$geno_mod == M1)
      loc_b <- which(mod_list[[geno2]]$geno_mod == M2)
      
      if (loc_a == 1) {
        M1_i <- 0
        M1_f <- mod_list[[geno1]][mod_list[[geno1]]$geno_mod == M1,"end_position"]}
      
      if (loc_a > 1) {
        M1_i <- mod_list[[geno1]][loc_a-1,"end_position"]
        M1_f <- mod_list[[geno1]][mod_list[[geno1]]$geno_mod == M1,"end_position"]}
      
      if (loc_b == 1) {
        M2_i <- 0
        M2_f <- mod_list[[geno2]][mod_list[[geno2]]$geno_mod == M2,"end_position"]}
      
      if (loc_b > 1) {
        M2_i <- mod_list[[geno2]][loc_b-1,"end_position"]
        M2_f <- mod_list[[geno2]][mod_list[[geno2]]$geno_mod == M2,"end_position"]}
      
      M1_cor <- mod_list[[geno1]][mod_list[[geno1]]$geno_mod == M1,"cor"]
      M2_cor <- mod_list[[geno2]][mod_list[[geno2]]$geno_mod == M2,"cor"]
      
      if (M1_cor > 0 & M2_cor > 0) {color = "green"}
      if (M1_cor < 0 & M2_cor < 0) {color = "blue"}
      if (M1_cor > 0 & M2_cor < 0) {color = "red"}
      if (M1_cor < 0 & M2_cor > 0) {color = "red"}
        
      circos.link(geno1, c(M1_i, M1_f), 
                  geno2, c(M2_i, M2_f), 
                  col=add_transparency(color, transp)) 
    }
    
    skip_these <- rbind(skip_these, modulez[,1:2])
    skip_these <- na.omit(skip_these)
  }
  
  
  # Highlight the genotypes
  for(i in 1:length(genoz)) {
    highlight.sector(sector.index = genoz[i], 
                     track.index = 1, 
                     col = geno_color[i], 
                     text = genoz[i], 
                     text.vjust = -2, 
                     niceFacing = TRUE)
  }
  
  circos.clear()
  
  dev.off()

}
```

```{r}

for (i in 1:length(tissuez)) {
  circos.plot(tissuez[i])
}

```






