---
title: "Age Clocks & Predictions"
author: "Aaron Mohammed"
output: github_document
---

```{r}

library(glmnet)
library(ggplot2)
library(ggbeeswarm)
library(showtext)
library(UpSetR)
library(unikn)
library(treemap)

data_path <- c('/Users/asm/Creighton/celegan/Bootstrap/_tissues_with_3_N2_timepoints')
main_path <- c('/Users/asm/Creighton/celegan/Predictions_and_Gene_Coef_2')
dir.create(main_path)

tissuez <- list.dirs(data_path,full.names=FALSE, recursive= FALSE)

# font_paths() 
#  font_add("arial","/System/Library/Fonts/Supplemental/Arial.ttf")

```

```{r}

gene.coef.and.predictions <- function(tissue) {
  
  tissue_dir <- file.path(data_path, tissue)
  output_dir <- file.path(main_path, tissue)
  dir.create(output_dir)
  
  ################################# N2 Model ##################################
  
  read.csv(file.path(tissue_dir,'N2_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'N2_Day_6.csv')) -> day6
  read.csv(file.path(tissue_dir,'N2_Day_12.csv')) -> day12
  read.csv(file.path(tissue_dir,'N2_Day_14.csv')) -> day14
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  rownames(day12) <- day12$X
  rownames(day14) <- day14$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  day12[2:102]->day12
  day14[2:102]->day14
  
  all <- cbind(day1,day6,day12,day14)
  expression <- log(t(all)*100000/colSums(all))
  t(t(c(rep(1,101),rep(6,101),rep(12,101),rep(14,101))))->true_age
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_N2 <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_N2,file.path(output_dir, "R2_N2.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_N2.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_N2.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_N2.csv"))
  
  ############################### LIPL4 Model #################################
  
  read.csv(file.path(tissue_dir,'LIPL4_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'LIPL4_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_LIPL4 <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_LIPL4,file.path(output_dir, "R2_LIPL4.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_LIPL4.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_LIPL4.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_LIPL4.csv"))
  
  ############################### DAF2 Model ##################################
  
  read.csv(file.path(tissue_dir,'DAF2_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'DAF2_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_DAF2 <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_DAF2,file.path(output_dir, "R2_DAF2.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_DAF2.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_DAF2.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_DAF2.csv"))
  
  ############################### RSKS1 Model #################################
  
  read.csv(file.path(tissue_dir,'RSKS1_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'RSKS1_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_RSKS1 <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_RSKS1,file.path(output_dir, "R2_RSKS1.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_RSKS1.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_RSKS1.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_RSKS1.csv"))
  
  ################################ BW Model ###################################
  
  read.csv(file.path(tissue_dir,'BW_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'BW_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_BW <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_BW,file.path(output_dir, "R2_BW.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_BW.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_BW.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_BW.csv"))
  
  ############################### DLON Model ##################################
  
  read.csv(file.path(tissue_dir,'DLON_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'DLON_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit <- cv.glmnet(expression, true_age)
  R2_DLON <- cvfit$glmnet.fit$dev.ratio[cvfit$index[1]] #R2
  write.csv(R2_DLON,file.path(output_dir, "R2_DLON.csv"))
  saveRDS(cvfit,file.path(output_dir, "model_DLON.RDS"))
  
  # Gene coefficients 
  coef(cvfit,s = "lambda.min")-> coefout
  coefout[,1]->test2
  data.frame(test2)->test3
  data.frame(gene=rownames(day1),value=test3[2:nrow(test3),])-> out
  write.csv(out, file.path(output_dir, "gene_coef_DLON.csv"))
  
  # Prediction
  predict(cvfit, newx = expression,s = "lambda.min") -> predicted_age
  cbind(predicted_age,true_age)->predictionout
  write.csv(predictionout, file.path(output_dir, "pred_DLON.csv"))
  
  #############################################################################
  
  # Plot N2
  read.csv(file.path(output_dir, 'pred_N2.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_N2, digits = 2))
  predictions$title <- paste(c("N2"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 2, y = 12, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 3.26, y = 11.9, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,16) + 
    ylim(0,16)
  
  pdf(file.path(output_dir,"predicted_ages_N2.pdf"))
  print(plot)
  dev.off()
  
  # Plot LIPL4
  read.csv(file.path(output_dir, 'pred_LIPL4.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_LIPL4, digits = 2))
  predictions$title <- paste(c("LIPL4"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 1, y = 7.5, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 1.85, y = 7.45, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,10) + 
    ylim(0,10)
  
  pdf(file.path(output_dir,"predicted_ages_LIPL4.pdf"))
  print(plot)
  dev.off()
  
  # Plot DAF2
  read.csv(file.path(output_dir, 'pred_DAF2.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_DAF2, digits = 2))
  predictions$title <- paste(c("DAF2"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 1, y = 7.5, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 1.85, y = 7.45, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,10) + 
    ylim(0,10)
  
  pdf(file.path(output_dir,"predicted_ages_DAF2.pdf"))
  print(plot)
  dev.off()
  
  # Plot RSKS1
  read.csv(file.path(output_dir, 'pred_RSKS1.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_RSKS1, digits = 2))
  predictions$title <- paste(c("RSKS1"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 1, y = 7.5, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 1.85, y = 7.45, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,10) + 
    ylim(0,10)
  
  pdf(file.path(output_dir,"predicted_ages_RSKS1.pdf"))
  print(plot)
  dev.off()
  
  # Plot BW
  read.csv(file.path(output_dir, 'pred_BW.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_BW, digits = 2))
  predictions$title <- paste(c("BW"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 1, y = 7.5, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 1.85, y = 7.45, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,10) + 
    ylim(0,10)
  
  pdf(file.path(output_dir,"predicted_ages_BW.pdf"))
  print(plot)
  dev.off()
  
  # Plot DLON
  read.csv(file.path(output_dir, 'pred_DLON.csv')) -> predictions
  R2_for_ggplot <- paste(c("="), sep=" ", round(R2_DLON, digits = 2))
  predictions$title <- paste(c("DLON"), sep="_", tissue)
  
  plot <- ggplot(predictions, aes(X.1, lambda.min)) +
    geom_beeswarm(width = 0.6, height = 0.8, size= 0.5) + 
    xlab(c("True Age")) + 
    ylab(c("Predicted Age")) +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black", size = 1), 
          axis.text=element_text(size=14), axis.title=element_text(size=16), 
          title=element_text(size=20), plot.title= element_text(hjust = 0.5)) +
    geom_smooth(method=lm,se=FALSE, size= 0.5, col= 'red') + 
    annotate("text", x = 1, y = 7.5, label = expression(R^2), size= 5.5) + 
    annotate("text", x = 1.85, y = 7.45, label = R2_for_ggplot, size= 5.5) + 
    facet_grid(. ~ title) + 
    theme(strip.background = element_rect(fill="red", size= 1.5), 
          strip.text = element_text(size=18, face="bold", colour="black")) +
    xlim(0,10) + 
    ylim(0,10)
  
  pdf(file.path(output_dir,"predicted_ages_DLON.pdf"))
  print(plot)
  dev.off()

}

```

```{r}

for (i in 1:length(tissuez)){
gene.coef.and.predictions(tissuez[i])
}

```

```{r}

wild.models <- function (tissue) {
  
  tissue_dir <- file.path(data_path, tissue)
  output_dir <- file.path(main_path, "_Wild_type_models", tissue)
  dir.create(output_dir)

  ################################# N2 Model ##################################

  read.csv(file.path(tissue_dir,'N2_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'N2_Day_6.csv')) -> day6
  read.csv(file.path(tissue_dir,'N2_Day_12.csv')) -> day12
  read.csv(file.path(tissue_dir,'N2_Day_14.csv')) -> day14
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  rownames(day12) <- day12$X
  rownames(day14) <- day14$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  day12[2:102]->day12
  day14[2:102]->day14
  
  all <- cbind(day1,day6,day12,day14)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101),rep(12,101),rep(14,101))))
  
  cvfit_N2 <- cv.glmnet(expression, true_age)
  
  # LIPL4
  read.csv(file.path(tissue_dir,'LIPL4_Day_6.csv'))->LIPL4_day6
  
  LIPL4_day6[2:102] -> LIPL4_day6
  
  expression <- log(t(LIPL4_day6)*100000/colSums(LIPL4_day6))
  predicted_age <- predict(cvfit_N2, newx = expression,s = "lambda.min")
  true_age <- t(t(c(rep(6,101))))
  predictionout <- cbind(predicted_age,true_age)
  write.csv(predictionout,file.path(output_dir, "pred_LIPL4_model_N2.csv"))
  
  # DAF2
  read.csv(file.path(tissue_dir,'DAF2_Day_6.csv'))->DAF2_day6
  
  DAF2_day6[2:102]->DAF2_day6
  
  expression <- log(t(DAF2_day6)*100000/colSums(DAF2_day6))
  predicted_age <- predict(cvfit_N2, newx = expression,s = "lambda.min")
  true_age <- t(t(c(rep(6,101))))
  predictionout <- cbind(predicted_age,true_age)
  write.csv(predictionout,file.path(output_dir, "pred_DAF2_model_N2.csv"))
  
  # RSKS1
  read.csv(file.path(tissue_dir,'RSKS1_Day_6.csv'))->RSKS1_day6
  
  RSKS1_day6[2:102]->RSKS1_day6
  
  expression <- log(t(RSKS1_day6)*100000/colSums(RSKS1_day6))
  predicted_age <- predict(cvfit_N2, newx = expression,s = "lambda.min")
  true_age <- t(t(c(rep(6,101))))
  predictionout <- cbind(predicted_age,true_age)
  write.csv(predictionout,file.path(output_dir, "pred_RSKS1_model_N2.csv"))
  
  ################################## BW Model #################################
  
  read.csv(file.path(tissue_dir,'BW_Day_1.csv')) -> day1
  read.csv(file.path(tissue_dir,'BW_Day_6.csv')) -> day6
  
  rownames(day1) <- day1$X
  rownames(day6) <- day6$X
  
  day1[2:102]->day1
  day6[2:102]->day6
  
  all <- cbind(day1,day6)
  expression <- log(t(all)*100000/colSums(all))
  true_age <- t(t(c(rep(1,101),rep(6,101))))
  
  cvfit_BW <- cv.glmnet(expression, true_age)
  
  # DLON
  read.csv(file.path(tissue_dir,'DLON_Day_6.csv'))->DLON_day6
  
  DLON_day6[2:102]->DLON_day6
  
  expression <- log(t(DLON_day6)*100000/colSums(DLON_day6))
  predicted_age <- predict(cvfit_BW, newx = expression,s = "lambda.min")
  true_age <- t(t(c(rep(6,101))))
  predictionout <- cbind(predicted_age,true_age)
  write.csv(predictionout,file.path(output_dir, "pred_DLON_model_BW.csv"))
      
}

```

```{r}

for (i in 1:length(tissuez)){
wild.models(tissuez[i])
}

```

```{r}

LIPL4_ <- data.frame(matrix(ncol = 3, nrow = length(tissuez)))

for (i in 1:length(tissuez)) {
  
  dir <- file.path(main_path, "_Wild_type_models", tissuez[i])
  
  LIPL4_D6 <- read.csv(file.path(dir, "pred_LIPL4_model_N2.csv"))
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min != Inf, ]
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min != -Inf, ]
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min > 0, ]
  LIPL4_stats <- t(as.data.frame(unclass(summary(LIPL4_D6$lambda.min))))
  LIPL4_[i, ] <- LIPL4_stats[ , c(2,3,5)]

}

rownames(LIPL4_) <- tissuez
colnames(LIPL4_) <- c('Q1','Median','Q3')

rownames(LIPL4_[order(LIPL4_$Median, decreasing = TRUE),]) -> ordered_names_for_LIPL4

# LIPL4
LIPL4 <- {}

for (i in 1:length(tissuez)) {

  dir <- file.path(main_path, "_Wild_type_models", tissuez[i])
  
  LIPL4_D6 <- read.csv(file.path(dir, "pred_LIPL4_model_N2.csv"))
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min != Inf, ]
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min != -Inf, ]
  LIPL4_D6 <- LIPL4_D6[LIPL4_D6$lambda.min > 0, ]
  LIPL4_D6 <- as.data.frame(LIPL4_D6[,2])
  LIPL4_D6[,2] <- tissuez[i]
  colnames(LIPL4_D6) <- c('lambda.min','Tissue')
  
  LIPL4[[i]] <- LIPL4_D6

}

LIPL4 <- do.call(rbind, LIPL4)

LIPL4$Tissue <- factor(LIPL4$Tissue , levels=ordered_names_for_LIPL4)

LIPL4[,3] <- rep(c("LIPL4"),nrow(LIPL4))
colnames(LIPL4) <- c('lambda.min','Tissue','Genotype')

# DAF2
DAF2 <- {}

for (i in 1:length(tissuez)) {
  
  dir <- file.path(main_path, "_Wild_type_models", tissuez[i])

  DAF2_D6 <- read.csv(file.path(dir, "pred_DAF2_model_N2.csv"))
  DAF2_D6 <- DAF2_D6[DAF2_D6$lambda.min != Inf, ]
  DAF2_D6 <- DAF2_D6[DAF2_D6$lambda.min != -Inf, ]
  DAF2_D6 <- DAF2_D6[DAF2_D6$lambda.min > 0, ]
  DAF2_D6 <- as.data.frame(DAF2_D6[,2])
  DAF2_D6[,2] <- tissuez[i]
  colnames(DAF2_D6) <- c('lambda.min','Tissue')
  
  DAF2[[i]] <- DAF2_D6
}

DAF2 <- do.call(rbind, DAF2)

DAF2$Tissue <- factor(DAF2$Tissue , levels=ordered_names_for_LIPL4)

DAF2[,3] <- rep(c("DAF2"),nrow(DAF2))
colnames(DAF2) <- c('lambda.min','Tissue','Genotype')

# RSKS1
RSKS1 <- {}

for (i in 1:length(tissuez)) {
  
  dir <- file.path(main_path, "_Wild_type_models", tissuez[i])

  RSKS1_D6 <- read.csv(file.path(dir, "pred_RSKS1_model_N2.csv"))
  RSKS1_D6 <- RSKS1_D6[RSKS1_D6$lambda.min != Inf, ]
  RSKS1_D6 <- RSKS1_D6[RSKS1_D6$lambda.min != -Inf, ]
  RSKS1_D6 <- RSKS1_D6[RSKS1_D6$lambda.min > 0, ]
  RSKS1_D6 <- as.data.frame(RSKS1_D6[,2])
  RSKS1_D6[,2] <- tissuez[i]
  colnames(RSKS1_D6) <- c('lambda.min','Tissue')
  
  RSKS1[[i]] <- RSKS1_D6
}

RSKS1 <- do.call(rbind, RSKS1)

RSKS1$Tissue <- factor(RSKS1$Tissue , levels=ordered_names_for_LIPL4)

RSKS1[,3] <- rep(c("RSKS1"),nrow(RSKS1))
colnames(RSKS1) <- c('lambda.min','Tissue','Genotype')

# DLON
DLON <- {}

for (i in 1:length(tissuez)) {

  dir <- file.path(main_path, "_Wild_type_models", tissuez[i])
  
  DLON_D6 <- read.csv(file.path(dir, "pred_DLON_model_BW.csv"))
  DLON_D6 <- DLON_D6[DLON_D6$lambda.min != Inf, ]
  DLON_D6 <- DLON_D6[DLON_D6$lambda.min != -Inf, ]
  DLON_D6 <- DLON_D6[DLON_D6$lambda.min > 0, ]
  DLON_D6 <- as.data.frame(DLON_D6[,2])
  DLON_D6[,2] <- tissuez[i]
  colnames(DLON_D6) <- c('lambda.min','Tissue')
  
  DLON[[i]] <- DLON_D6

}

DLON <- do.call(rbind, DLON)

DLON$Tissue <- factor(DLON$Tissue , levels=ordered_names_for_DLON)

DLON[,3] <- rep(c("DLON"),nrow(DLON))
colnames(DLON) <- c('lambda.min','Tissue','Genotype')

# Plot

df_list <- list(LIPL4, DAF2, RSKS1, DLON)
all_genotypes <- Reduce(function(x, y) merge(x, y, all=TRUE, sort=FALSE), df_list)  

all_genotypes$Genotype <- factor(all_genotypes$Genotype , levels= c("LIPL4","DAF2","RSKS1","DLON"))

blue <- c('#0066CC')
orange <- c('#CC9900')
pink <- c('#990066')
green <- c('#009900')

palet <- c(blue,orange,pink,green)
my_colors <- usecol(palet)

All_genotypes_boxplot <- ggplot(all_genotypes, aes(x=lambda.min, y=Tissue))+
  geom_boxplot(coef=0, aes(fill = Genotype), outlier.size=0.2, outlier.alpha=0.5) + 
  geom_jitter(size=0.2, alpha=0.5) +
  geom_vline(xintercept = 6, linetype="solid", color = "red", size=0.5) +
  scale_fill_manual(values = my_colors) +
  scale_x_continuous(limits = c(0, 8), expand = c(0, 0), n.breaks=3) + 
  xlab(c('Age')) + 
  ggtitle(c('Predicted Age')) + 
  facet_grid( ~ Genotype) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(color = "black", size = 0.5), 
        axis.text=element_text(size=14, color="black"), 
        axis.title=element_text(size=20), 
        title=element_text(size=22), 
        plot.title= element_text(hjust = 0.5), 
        legend.text=element_text(size=rel(0.8)),
        legend.title=element_blank(), 
        legend.key.size= unit(0.7,'cm'),
        panel.spacing = unit(1, "lines"), 
        strip.background=element_blank(), 
        strip.text=element_blank())

pdf(file.path(main_path, "_Wild_type_models", "predicted_ages.pdf"),height = 5, width = 8)
All_genotypes_boxplot  
dev.off()

```

```{r}

filter.gene.coef <- function (tissue) {
  
  tissue_dir <- file.path(main_path, tissue)
  dir <- file.path(main_path, tissue, "gene_corr")
  dir.create(dir)
  
  N2_dir <- file.path(dir, "N2")
  LIPL4_dir <- file.path(dir, "LIPL4")
  DAF2_dir <- file.path(dir, "DAF2")
  RSKS1_dir <- file.path(dir, "RSKS1")
  BW_dir <- file.path(dir, "BW")
  DLON_dir <- file.path(dir, "DLON")
  
  dirz <- c(N2_dir, LIPL4_dir, DAF2_dir, RSKS1_dir, BW_dir, DLON_dir)
  for (i in 1:length(dirz)) {dir.create(dirz[i])}
  
  files <- dir(tissue_dir, "gene_coef")
  
  for (i in 1:length(files)) {
    
    file_name <- files[i]
    geno <- gsub("gene_coef_","",file_name)
    geno <- gsub(".csv","",geno)
    
    read.csv(file.path(tissue_dir, file_name)) -> gene_coef
    
    gene_coef_nonzeros <- gene_coef[gene_coef$value != 0,]
    gene_coef_nonzeros <- gene_coef_nonzeros[,2:3]
    
    gene_coef_neg <- gene_coef_nonzeros[gene_coef_nonzeros$value < 0, ]
    gene_coef_pos <- gene_coef_nonzeros[gene_coef_nonzeros$value > 0, ]
    
    rownames(gene_coef_neg) <- NULL
    rownames(gene_coef_pos) <- NULL
    
    write.csv(gene_coef_neg, file.path(dir, geno, 'neg.csv'))
    write.csv(gene_coef_pos, file.path(dir, geno, 'pos.csv'))
  
  }

}

```

```{r}

for (i in 1:length(tissuez)) {
filter.gene.coef(tissuez[i])
}

```

```{r}

# Negative correlation

dir <- file.path(main_path, tissuez[1], "gene_corr")
geno <- list.dirs(dir, full.names= FALSE)
geno <- geno[2:length(geno)]
neg <- vector(mode = "list", length(geno))
names(neg) <- geno

get.neg <- function (geno, tissue) {
  tissue_dir <- file.path(main_path, tissue)
  geno_dir <- file.path(tissue_dir, "gene_corr", geno)
  neg_coef <- read.csv(file.path(geno_dir, 'neg.csv'))
  neg_coef <- neg_coef[,2]
  return(neg_coef)
}

for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
    neg[[i]][[j]] <- get.neg(geno[i],tissuez[j])
  }
  names(neg[[i]]) <- tissuez
}

neg -> neg1
  
for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
  neg1[[i]][[j]] <- c(neg1[[i]][[j]], rep(NA,max(lengths(neg1[[i]]))-length(neg1[[i]][[j]])))
  }
}

upset_path <- file.path(main_path, "upset")
dir.create(upset_path)

for (i in 1:length(geno)) {
  neg_df <- as.data.frame(do.call(cbind, neg1[[i]]))
  unlisted <- unlist(neg_df)
  occurences <- as.data.frame(table(unlisted))
  occurences <- occurences[order(occurences$Freq, decreasing=TRUE),]
  row.names(occurences) <- NULL
  file_name <- paste0("neg_freq", sep= "_", geno[i], sep= ".", "csv")
  write.csv(occurences,file.path(upset_path, file_name))
}

for (i in 1:length(geno)) {
  file_name <- paste0("neg_upset", sep= "_", geno[i], sep= ".", "pdf")
  pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
  print(upset(fromList(neg[[i]]), nsets = length(tissuez), order.by = "degree", 
        text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), nintersects = NA))
  dev.off()
}

# # N2
# for (i in 5) {
#   file_name <- paste0("neg_upset", sep= "_", geno[i], sep= "_", "figure_50", sep= ".", "pdf")
#   pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
#   print(upset(fromList(neg[[i]]), nsets = length(tissuez), order.by = "degree",
#         text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), mainbar.y.max= 50))
#   dev.off()
# }

```

```{r}


# Positive correlation 

dir <- file.path(main_path, tissuez[1], "gene_corr")
geno <- list.dirs(dir, full.names= FALSE)
geno <- geno[2:length(geno)]
pos <- vector(mode = "list", length(geno))
names(pos) <- geno

get.pos <- function (geno, tissue) {
  tissue_dir <- file.path(main_path, tissue)
  geno_dir <- file.path(tissue_dir, "gene_corr", geno)
  pos_coef <- read.csv(file.path(geno_dir, 'pos.csv'))
  pos_coef <- pos_coef[,2]
  return(pos_coef)
}

for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
    pos[[i]][[j]] <- get.pos(geno[i],tissuez[j])
  }
  names(pos[[i]]) <- tissuez
}

pos -> pos1
  
for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
  pos1[[i]][[j]] <- c(pos1[[i]][[j]], rep(NA,max(lengths(pos1[[i]]))-length(pos1[[i]][[j]])))
  }
}

upset_path <- file.path(main_path, "upset")
dir.create(upset_path)

for (i in 1:length(geno)) {
  pos_df <- as.data.frame(do.call(cbind, pos1[[i]]))
  unlisted <- unlist(pos_df)
  occurences <- as.data.frame(table(unlisted))
  occurences <- occurences[order(occurences$Freq, decreasing=TRUE),]
  row.names(occurences) <- NULL
  file_name <- paste0("pos_freq", sep= "_", geno[i], sep= ".", "csv")
  write.csv(occurences,file.path(upset_path, file_name))
}

for (i in 1:length(geno)) {
  file_name <- paste0("pos_upset", sep= "_", geno[i], sep= ".", "pdf")
  pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
  print(upset(fromList(pos[[i]]), nsets = length(tissuez), order.by = "degree", 
        text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), nintersects = NA))
  dev.off()
}

# # N2
# for (i in 5) {
#   file_name <- paste0("pos_upset", sep= "_", geno[i], sep= "_", "figure_50", sep= ".", "pdf")
#   pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
#   print(upset(fromList(pos[[i]]), nsets = length(tissuez), order.by = "degree",
#         text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), mainbar.y.max= 50))
#   dev.off()
# }

```

```{r}

both <- vector(mode = "list", length(geno))
names(both) <- geno

for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
    both[[i]][[j]] <- c(pos[[i]][[j]], neg[[i]][[j]])
  }
  names(both[[i]]) <- tissuez
}

both -> both1
  
for (i in 1:length(geno)) {
  for (j in 1:length(tissuez)) {
  both1[[i]][[j]] <- c(both1[[i]][[j]], rep(NA,max(lengths(both1[[i]]))-length(both1[[i]][[j]])))
  }
}

upset_path <- file.path(main_path, "upset")
dir.create(upset_path)

for (i in 1:length(geno)) {
  both_df <- as.data.frame(do.call(cbind, both1[[i]]))
  unlisted <- unlist(both_df)
  occurences <- as.data.frame(table(unlisted))
  occurences <- occurences[order(occurences$Freq, decreasing=TRUE),]
  row.names(occurences) <- NULL
  file_name <- paste0("both_freq", sep= "_", geno[i], sep= ".", "csv")
  write.csv(occurences,file.path(upset_path, file_name))
}

for (i in 1:length(geno)) {
  file_name <- paste0("both_upset", sep= "_", geno[i], sep= ".", "pdf")
  pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
  print(upset(fromList(both[[i]]), nsets = length(tissuez), order.by = "degree", 
        text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), nintersects = NA))
  dev.off()
}


# N2
for (i in 5) {
  file_name <- paste0("both_upset", sep= "_", geno[i], sep= "_", "figure", sep= ".", "pdf")
  pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
  print(upset(fromList(both[[i]]), nsets = length(tissuez), order.by = "degree",
        text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), nintersects = 63, point.size = 1.5))
  dev.off()
}

# for (i in 5) {
#   file_name <- paste0("both_upset", sep= "_", geno[i], sep= "_", "figure_50", sep= ".", "pdf")
#   pdf(file.path(upset_path, file_name), width = 9, height = 5, bg = "white")
#   print(upset(fromList(both[[i]]), nsets = length(tissuez), order.by = "degree",
#         text.scale = c(1.5, 1.1, 1.1,1.1, 1.1, 1.1), mainbar.y.max= 50))
#   dev.off()
# }


```

```{r}

# Tree maps

tree_dir <- '/Users/asm/Creighton/celegan/Tree_maps'

# Negative
for (i in 1:length(tissuez)) {
  for (j in 1:length(geno)) {
    tissue_dir <- file.path(main_path, tissuez[i])
    geno_dir <- file.path(tissue_dir, "gene_corr", geno[j])
    neg_coef <- read.csv(file.path(geno_dir, 'neg.csv'))
    neg_coef <- neg_coef[,-1]
    neg_coef$value <- neg_coef$value * -1
    
    title <- paste0(tissuez[i], sep= " ", geno[j], sep= " ", "Negative")
    file_name <- paste0("Negative_TM", sep= "_", tissuez[i], sep= "_", geno[j], sep= ".", "pdf")
    
    pdf(file.path(geno_dir, file_name), width = 7, height = 7, bg = "white")
    treemap(neg_coef, index="gene", vSize="value", type="index", title= title, 
fontface.labels= "italic")
    dev.off()
  }
}

# Positive
for (i in 1:length(tissuez)) {
  for (j in 1:length(geno)) {
    tissue_dir <- file.path(main_path, tissuez[i])
    geno_dir <- file.path(tissue_dir, "gene_corr", geno[j])
    pos_coef <- read.csv(file.path(geno_dir, 'pos.csv'))
    pos_coef <- pos_coef[,-1]
    
    title <- paste0(tissuez[i], sep= " ", geno[j], sep= " ", "Positive")
    file_name <- paste0("Positive_TM", sep= "_", tissuez[i], sep= "_", geno[j], sep= ".", "pdf")
    
    pdf(file.path(geno_dir, file_name), width = 7, height = 7, bg = "white")
    treemap(pos_coef, index="gene", vSize="value", type="index", title= title, 
fontface.labels= "italic")
    dev.off()
  }
}

```














